import numpy as np
c = np.array([[1,1,1],[2,2,2],[3,3,3]])
d = np.array([[4,4,4],[5,5,5],[6,6,6]])
e = np.concatenate((c,d),axis=0)
print("========================")
print(c)
print("========================")
print(d)
print("========================")
print(e)
print("========================")